
TRZISTE = "BTC-USDT"
IP_PROSODY = "192.168.1.11"

PERIOD_CIJENE = 1
PROMJENA_CIJENE = 0.01

MARKET_BOT_MAINTAIN_VALUE = 100000
MARKET_BOT_PROFIT_MARGIN = 0.01
MARKET_BOT_MIN_PROFIT_MARGIN = 0.05

TRZISTE_BASE = TRZISTE.split("-")[0]
TRZISTE_QUOTE = TRZISTE.split("-")[1]

KLIJENT_PROFIT_MARGIN = 0.01
